import csv
from io import StringIO


def export_prp_csv(step_rows):
    output = StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "기준일",
        "LINE",
        "PRP",
        "AREA",
        "LAYER",
        "STEP",
        "SKIPRULE",
        "DESCRIPT",
        "RECIPE",
        "EQPGROUP",
        "CHAM정보",
        "TYPE",
        "BODY호환",
        "CHAM호환",
        "BODY수",
        "CHAM수",
        "호환구분",
        "상시여부",
        "주요여부",
        "호환계획여부",
        "계획_호환EQPBODY명",
        "계획_호환EQPCHAM명",
        "계획_호환완료계획일",
        "계획_평가LotID",
        "계획_평가단계",
        "계획_비고",
        "TIP미등록 호환Path 여부",
        "미등록TIP호환Path_상시/비상시",
        "미등록TIP호환Path_주요/비주요",
        "미등록TIP호환Path_호환EQPBODY명",
        "미등록TIP호환Path_호환EQPCHAM명",
        "BODY호환_TIP고려",
        "CHAM호환_TIP고려",
        "BODY호환확보수_TIP고려",
        "CHAM호환확보수_TIP고려",
        "TIP",
        "CHILDEQP",
    ])

    for row in step_rows:
        writer.writerow([
            row["snap_date"],
            row["lineid"],
            row["processid"],
            row["areaname"],
            row["layerid"],
            row["stepseq"],
            row["skiprule"],
            row["descript"],
            row["recipeid"],
            row["eqpgroup"],
            row["cham_display"],
            row["stepseq_type"],
            row["body_compat_flag"],
            row["cham_compat_flag"],
            row["body_path_count"],
            row["cham_path_count"],
            row["compat_type"],
            "Y" if row["has_always"] else "N",
            "Y" if row["has_major"] else "N",
            "Y" if row["has_plan"] else "N",
            row["plan_body_names"],
            row["plan_cham_names"],
            row["plan_due_dates"],
            row["plan_eval_lot_ids"],
            row["plan_eval_stages"],
            row["plan_memos"],
            row["tip_missing_flag"],
            row["tip_missing_always"],
            row["tip_missing_major"],
            row["tip_missing_body"],
            row["tip_missing_cham"],
            row["body_compat_tip"],
            row["cham_compat_tip"],
            row["body_compat_count_tip"],
            row["cham_compat_count_tip"],
            row["tip"],
            row["childeqp"],
        ])

    return output.getvalue()
